.TH "SPIKE" "8" "2014-07-14" "GNU Pony" "GNU Pony Manual"
.SH NAME
spike - a package manager running on top of git
.SH "SYNOPSIS"
.B
spike
.I
<COMMAND>
[\fIOPTION\fR]... [\fIARG\fR]...
.SH "DESCRIPTION"
.PP
.B
spike
is used to spike your system with new ponies and new versions of ponies
(known on other systems as packages).
.B
spike
uses individual commands to affect the ponies in different ways.
Each command is mutually exclusive,
i.e. only one command can be run at a time.
.PP
Ponies are installed using so-called 'scrolls'.
These are written
(for maximum simplicity and portability)
in Python 3.
A collection of these are distributed with
.B
spike
and updated when
.B
spike
is updated,
but you can add scroll repositories on your local installation at will.
.PP
.B
spike
has the capability of not only installing ponies,
but also archiving installations
(for easy rollback in case of system breakage,
a must-have feature on unstable operating systems).
.SH COMMANDS
.PP
\fB\-B, \-\-bootstrap\fR
.RS 4
Bootstrap
.B
spike
and the scoll archives,
updating them to the latest available version.
Passing
\fI\-\-no\-verify\fR
will disable signature verification
(not recommended).
.RE
.PP
\fB\-F, \-\-find\fR [PATTERN... | FILE...]
.RS 4
Look through
\fBspike\fR's
repositories for scrolls,
either matching the given file name pattern,
or that are associated with ponies that own the given file
(if the
\fI\-\-owner\fR
flag is given).
Using the
\fI\-\-written\fR
flag will limit the search to only installed or uninstalled ponies.
.PP
The pattern is defined as 'repo/category/scroll' and is right associative,
so 'ed' will search all categories in all repos for a scroll containing 'ed' in its filename,
while 'ed//' can be used to search for all the scrolls in all the categories in a repository which contains 'ed' in its name.
.RE
.PP
\fB\-W, \-\-write\fR SCROLL...
.RS 4
Install a pony using the pony's scroll.
Running with either the
\fI\-\-asdep\fR
or
\fI\-\-asexplicit\fR
will install the pony with the according designation.
\fI\-\-pinpal\fR
and
\fI\-\-private\fR
may be used to modify the install location.
\fI\-\-nodep\fR
will avoid installing any dependencies the pony relies on
(not recommended),
and
\fI\-\-force\fR
will ignore any file conflicts that may arise during installation.
This command accepts
\fI\-\-shred\fR.
.RE
.PP
\fB\-U, \-\-update\fR
.RS 4
Update the ponies to their newest versions.
\fI\-\-pinpal\fR
and
\fI\-\-private\fR
may be used to change the root location.
\fI\-\-ignore\fR
will not update the specified ponies.
This command accepts
\fI\-\-shred\fR.
.RE
.PP
\fB\-E, \-\-erase\fR PONY...
.RS 4
Uninstall a pony from the system.
The root may be changed with either
\fI\-\-pinpal\fR
or
\fI\-\-private\fR.
\fI\-\-shred\fR
will ensure secure removal of the ponies.
.RE
.PP
\fB\-\-demote\fR PONY...
.RS 4
Demote a pony to being treated as a pony installed as a dependency.
Accepts
\fI\-\-private\fR.
.RE
.PP
\fB\-\-promote\fR PONY...
.RS 4
Promote a pony to being treated as a pony installed explicitly.
Accepts
\fI\-\-private\fR.
.RE
.PP
\fB\-X, \-\-ride\fR PONY
.RS 4
Run a pony.
Accepts
\fI\-\-private\fR.
.RE
.PP
\fB\-R, \-\-read\fR SCROLL...
.RS 4
Get information contained in a scroll.
Results can be filtered using
\fI\-\-written\fR.
To get a specific field, use the
\fI\-\-info\fR
flag.
Providing the
\fI\-\-list\fR
flag will list all the files claimed by the pony associated with the scroll.
.RE
.PP
\fB\-C, \-\-claim\fR FILE... PONY
.RS 4
Claim some files as belonging to a pony.
Using either
\fI\-\-recursive\fR
or
\fI\-\-entire\fR
will modify how directories are claimed.
\fI\-\-force\fR
will ignore any conflicts.
Accepts
\fI\-\-private\fR.
.RE
.PP
\fB\-D, \-\-disclaim\fR FILE... PONY
.RS 4
Disclaim some files as not belonging to a pony.
Using
\fI\-\-recursive\fR
will descend into directories.
Accepts
\fI\-\-private\fR.
.RE
.PP
\fB\-A, \-\-archive\fR ARCHIVE
.RS 4
Create an archive of everything that is currently installed.
Flag
\fI\-\-scrolls\fR
to only archive scrolls and not installed files.
.RE
.PP
\fB\-\-restore\-archive\fR ARCHIVE
.RS 4
Roll back to an archived system state.
Either the
\fI\-\-downgrade\fR
or
\fI\-\-upgrade\fR
option may be used to only perform that type of operation.
One of
\fI\-\-shared\fR,
\fI\-\-full\fR,
and
\fI\-\-old\fR
may be used for finer control over the restoration.
Accepts
\fI\-\-shred\fR.
.RE
.PP
\fB\-N, \-\-clean\fR
.RS 4
Uninstall unneeded ponies from the system.
Accepts.
\fI\-\-private\fR
and
\fI\-\-shred\fR.
.RE
.PP
\fB\-P, \-\-proofread\fR SCROLL...
.RS 4
Verify that a scroll is well-formed.
Note that this is only an integrity check,
and will not check a scroll's operations for correctness.
.RE
.PP
\fB\-S, \-\-example\-shot\fR SCROLL...
.RS 4
Display the example screenshots for a scroll using an image viewer
(\fBspike\fR
attempts a default image viewer,
but one may be provided with
\fI\-\-viewer\fR).
\fI\-\-all\-at\-once\fR
is useful when multiple scrolls are passed in.
.RE
.PP
\fB\-I, \-\-interactive\fR
.RS 4
Start
.B
spike
in an interactive,
graphical mode.
This mode only supports (un)installation.
Accepts
\fI\-\-shred\fR.
.RE
.PP
\fB\-3, \-\-sha3sum\fR FILE...
.RS 4
Calculate the SHA3 checksum for a file.
Note that if multiple files are passed,
the resulting checksums may
NOT BE RETURNED IN THE SAME ORDER
as their corresponding files.
.RE
.SH OPTIONS
.TP
\fB\-o, \-\-owner\fR
Find the pony owner(s) of a file.
.TP
\fB\-w, \-\-written\fR "\fIy\fR" | "\fIn\fR"
Filter by installed or not installed ponies
(or scrolls of ponies).
.TP
\fB\-\-pinpal\fR \fIROOT\fR
Change the root directory that
\fBspike\fR
uses when performing actions.
.TP
\fB\-u, \-\-private\fR
Perform pony actions in private.
.TP
\fB\-\-asdep\fR
Treat a pony as or change a pony to be marked as installed as a dependency.
Dependency is generic,
so the pony will not be associated with any other pony in particular.
.TP
\fB\-\-asexplicit\fR
Treat a pony as or change a pony to be marked as explicitly installed.
Remember to mark non-explicitly installed ponies as such if you wish to keep them around;
otherwise they might be expelled by a command such as
\fI--clean\fR.
.TP
\fB\-\-nodep\fR
Do not deal with dependencies when installing/modifying a pony.
.TP
\fB\-\-force\fR
Ignore potential conflicts when installing/modifying a pony or the system.
.TP
\fB\-i, \-\-ignore\fR \fIFILE\fR...
Ignore particular ponies when performing a command.
.TP
\fB\-l, \-\-list\fR
List files associated with a pony or scroll.
.TP
\fB\-f, \-\-info\fR \fIFIELD\fR...
Filter command output by specific fields.
.TP
\fB\-\-recursive\fR
Recursively perform a command that targets a directory.
.TP
\fB\-\-entire\fR
Recursively perform a command that targets a directory,
and remember that recursiveness for the future.
.TP
\fB\-s, \-\-scrolls\fR
Perform actions only on scrolls
(as opposed to ponies, the system, etc).
.TP
\fB\-\-shared\fR
Reinstall only with ponies that are currently installed as well as archived.
.TP
\fB\-\-full\fR
Uninstall ponies that are not archived.
.TP
\fB\-\-old\fR
Reinstall only the ponies that are not currently installed.
.TP
\fB\-\-downgrade\fR
Only perform downgrades on a pony.
.TP
\fB\-\-upgrade\fR
Only perform upgrades on a pony.
.TP
\fB\-\-shred\fR
Securely remove any data that is erased while executing a command.
This may take longer than a simple delete.
See
\fBshred\fR(1)
for more details.
.TP
\fB\-\-no\-verify\fR
Disable signature verification when performing actions on repositories.
This is NOT RECOMMENDED,
as it leaves your system vulnerable to rogue packages and updates.
.TP
\fB\-a, \-\-all\-at\-once\fR
Group together results into one output or action instead of breaking them up.
.TP
\fB\-\-viewer\fR \fIVIEWER\fR
Specify an image viewer to use for commands involving images.
.SH "AUTHORS"
.PP
Written by Mattias Andrée <maandree@member.fsf.org>.
.SH "SEE ALSO"
.TP
\fBshred\fR(1)
.SH "COPYRIGHT"
.PP
Copyright (C) 2012, 2013, 2014  Mattias Andrée
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
